//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classifier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Human
    {
        public int ID { get; set; }
        public byte[] HOG { get; set; }
        public int IsHuman { get; set; }
    }
}
